version: "3.8"

services:
  server:
    image: appset-rancher-projects-plugin
    restart: "no"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      API_TOKEN: "1234"
      RANCHER_SERVER: "${RANCHER_SERVER:-}"
      RANCHER_TOKEN: "${RANCHER_TOKEN:-}"
      
